# -*- coding: utf-8 -*-
"""PySpark - Google Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K1B6GOl_RY1gwUgN-UWb7adMVjh1dB-I

# Mastering Big Data with PySpark on Google Colab
---

> [Meduim](https://medium.com/@siladityaghosh/mastering-big-data-with-pyspark-on-google-colab-d3c924264ceb#:~:text=While%20local%20setups%20can%20be,on%20the%20ease%20of%20setup)
"""

!pip install findspark

import findspark
findspark.init()

from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("YourAppName").getOrCreate()

df_2 = spark.createDataFrame(
    [
        ("linha 1", 1, 10, 23),
        ("linha 2", 2, 11, 25),
        ("linha 3", 3, 12, 12),
        ("linha 4", 4, 13, 4),
        ("linha 5", 5, 14, 5)
    ],
    ["Linha", "jan/22", "fev/22", "mar/22"]
)

df_2.show()

df_2.createOrReplaceTempView("sql_sf")

spark.sql("""

select *
from sql_sf

""").show()

